package com.mulesoft.workshop.servicedesk;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.5.1
 * 2015-07-19T00:28:18.133-03:00
 * Generated source version: 2.5.1
 * 
 */
@WebService(targetNamespace = "http://www.mulesoft.com/AccountsService/", name = "AccountsService")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface AccountsService {

    @WebResult(name = "accountOutput", targetNamespace = "http://www.mulesoft.com/AccountsService/", partName = "response")
    @WebMethod(action = "http://www.mulesoft.com/AccountsService/createAccount")
    public AccountOutput createAccount(
        @WebParam(partName = "request", name = "accountInput", targetNamespace = "http://www.mulesoft.com/AccountsService/")
        AccountInput request
    );
}
