
package com.mulesoft.workshop.servicedesk;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;

import javax.xml.namespace.QName;

/**
 * This class was generated by Apache CXF 2.5.1
 * 2015-07-19T00:28:18.078-03:00
 * Generated source version: 2.5.1
 * 
 */
public final class AccountsService_AccountsServiceSOAP_Client {

    private static final QName SERVICE_NAME = new QName("http://www.mulesoft.com/AccountsService/", "AccountsService");

    private AccountsService_AccountsServiceSOAP_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = AccountsService_Service.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        AccountsService_Service ss = new AccountsService_Service(wsdlURL, SERVICE_NAME);
        AccountsService port = ss.getAccountsServiceSOAP();  
        
        {
        System.out.println("Invoking createAccount...");
        com.mulesoft.workshop.servicedesk.AccountInput _createAccount_request = null;
        com.mulesoft.workshop.servicedesk.AccountOutput _createAccount__return = port.createAccount(_createAccount_request);
        System.out.println("createAccount.result=" + _createAccount__return);


        }

        System.exit(0);
    }

}
